server:
  applicationName: test-gorm
  port: :8080


database:
  type: mysql
  host: localhost
  port: 3306
  username: root
  password: 123456
  dbname: test_gorm_db
  maxIdleConn: 10
  maxOpenConn: 30
  connMaxLifetime: 300
